# run: conda env create -f conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: bera39
channels:
  - appliedgrg
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - distributed
  - appliedgrg::bera_centerlines
  - geopandas
  - pip
  # - pip:
    # works for regular pip packages
    # - pyqtlet2
    # and for wheels
    # - http://URL_TO_THE_WHEEL.whl
  - pyogrio>=0.9.0
  # - pytorch::torchvision
  - pyqt
  - pyqtlet2
  - psutil
  - rioxarray
  - rpy2
  - r-essentials
  - r-lidr
  - r-rcsf
  - r-rlas
  - r-sf
  - r-sp
  - r-terra
  - scikit-image>=0.24.0
  - xarray-spatial
variables: