# run: conda env create -f conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: bera39
channels:
  - conda-forge
dependencies:
  - python=3.9
  - fiona
  - geopandas
  - gdal
  - leafmap
  - line_profiler
  - mamba
  - matplotlib
  - numba
  - numpy
  - Pillow
  - pip
  - pip:
    # works for regular pip packages
    - pyqtlet2
    # and for wheels
    # - http://URL_TO_THE_WHEEL.whl
  - pyqt
  - rasterio
  - ray-all
  - rioxarray
  - rpy2
  - r-base
  - r-essentials
  - r-lidr
  - r-terra
  - scikit-image
  - scipy
  - setuptools
  - shapely
  - sphinx
  - sphinx-tabs
  - sphinx-rtd-theme
  - spyder
  - xarray
  - xarray-spatial
variables: