# run: conda env create -f conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: bera39
channels:
  - appliedgrg
  - conda-forge
dependencies:
  - python=3.9
  - appliedgrg::label_centerlines
  - geopandas
  - matplotlib
  - pip
  # - pip:
    # works for regular pip packages
    # - pyqtlet2
    # and for wheels
    # - http://URL_TO_THE_WHEEL.whl
  - pyogrio
  # - pytorch::torchvision
  - pyqt
  - psutil
  - rioxarray
  - rpy2
  - r-essentials
  - r-lidr
  - r-terra
  - scikit-image
  - xarray-spatial
variables: