# run: conda env create -f conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: bera
channels:
  - conda-forge
dependencies:
  - click
  - future
  - setuptools
  - Pillow
  - fiona > 1.9.2
  - numpy
  - rasterio
  - shapely
  - gdal
  - pyqt
  - scipy
  - numba
  - xarray
  - rioxarray
  - scikit-image
  - sphinx
  - sphinx-rtd-theme
  - sphinx-tabs
  - xarray-spatial
  - whitebox
  - geopandas
  - pip
  - matplotlib
  - pyproj
variables: