# run: conda env create -f conda_environment.yml
# see also https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file
name: bera
channels:
  - conda-forge
dependencies:
  - python=3.10
  - fiona > 1.9.2
  - geopandas
  - leafmap
  - mamba
  - matplotlib
  - numba
  - numpy
  - Pillow
  - pip
    # works for regular pip packages
    - pyqtlet2
    # and for wheels
    # - http://URL_TO_THE_WHEEL.whl
  - pyqt
  - rasterio
  - rioxarray
  - scikit-image
  - scipy
  - setuptools
  - shapely
  - sphinx
  - sphinx-tabs
  - sphinx-rtd-theme
  - spyder
  - xarray
  - xarray-spatial
variables: