[project]
authors = ["Richard <502763+RichardQZeng@users.noreply.github.com>"]
channels = ["nodefaults", "appliedgrg", "conda-forge"]
description = "BERA Tools is toolset to extract and assess line features in forest"
name = "bera"
platforms = ["win-64"]
version = "0.1.0"

[tasks]
main_tk = "python main.py"
main = "python ./beratools/gui/main.py"

[dependencies]
python = "3.11.*"
bera_centerlines = { channel = "appliedgrg" }
pyqtlet2 = { channel = "appliedgrg" }
dask = "*"
dask-expr = "*"
distributed = "*"
fiona = "*"
gdal = "3.9.3.*"
geopandas = "*"
pyogrio = ">=0.9.0"
pyqt = "*"
psutil = "*"
rioxarray = "*"
rpy2 = "*"
r-essentials = "*"
r-lidr = "*"
r-rcsf = "*"
r-rlas = "*"
r-sf = "*"
r-sp = "*"
r-terra = "*"
scikit-image = ">=0.24.0"
tqdm = "*"
xarray-spatial = "*"
pip = "*"
