# https://levelup.gitconnected.com/publishing-your-python-package-on-conda-and-conda-forge-309a405740cf
# https://medium.com/analytics-vidhya/publish-a-python-package-to-conda-b352eb0bcb2e
package:
    name: "beratools"
    version: "0.1.0"

source:
    git_rev: 0.1.0
    git_url: git@github.com:RichardQZeng/BTools

requirements:
    host:
      - python
      - setuptools
    build:
      - python
      - setuptools
      - Pillow
      - fiona >1.9.2
      - numpy
      - rasterio
      - shapely
      - gdal
      - pyqt
      - scipy
      - numba
      - xarray
      - rioxarray
      - scikit-image
      - xarray-spatial
      - geopandas
      - pip
      - matplotlib
      - pyproj
      - leafmap
      - sphinx
      - sphinx-rtd-theme
      - sphinx-tabs

    about:
      home:
      license: MIT
      licensse_family: MIT
      license_file: LICENSE.txt
      summary: "Excellent BERA Tools"

    extra:
      recipe-maintainer:
        - Richard

    