{% set name = "BTools" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RichardQZeng/BTools/archive/{{ version }}.tar.gz
  sha256: 92c242fd57ded51f7ad3b203e4e8e6dc939df8eb9be66c36a8958492fbc68c35


build:
  entry_points:
    - BERATools = beratools.gui:gui_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - label_centerlines
    - geopandas
    - pip
    - pyogrio
    - psutil
    - pyqt
    - rioxarray
    - rpy2
    - r-essentials
    - r-lidr
    - r-rcsf
    - r-rlas
    - r-sf
    - r-sp
    - r-terra
    - scikit-image
    - xarray-spatial

test:
  imports:
    - beratools
  commands:
    - pip check
    - BERATools --help
  requires:
    - pip

about:
  home: https://github.com/RichardQZeng/BTools.git
  summary: An advanced forest line feature analysis platform
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - richard
