schema_version: 1

context:
  name: BERATools
  version: 0.2.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  git: https://github.com/RichardQZeng/BTools.git
  # tag: 0.2.0
  rev: 25408f2e1b2d46b500e491dde6abd599fcb6f88b

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - BERATools = beratools.gui:gui_main

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9
    - bera_centerlines
    - dask
    - dask-expr
    - distributed
    - fiona
    - gdal
    - geopandas
    - pip
    - pyogrio
    - psutil
    - pyqt
    - pyqtlet2
    - rioxarray
    - rpy2
    - r-essentials
    - r-lidr
    - r-rcsf
    - r-rlas
    - r-sf
    - r-sp
    - r-terra
    - scikit-image
    - tqdm
    - xarray-spatial

tests:
  - script:
      - pytest ./tests
    
    files:
      source:
        - tests/

    requirements:
      run:
        - pytest

  - python:
      imports:
        - beratools

about:
  summary: An advanced forest line feature analysis platform
  license: MIT
  license_file:
    - LICENSE
  homepage: https://github.com/RichardQZeng/BTools.git

extra:
  recipe-maintainers:
    - richard

